### ISSUE TITLE
"Kein Login auf Safari möglich"

### ISSUE THREAD

**Issue by felixblang** [MartinNiemllerSchule/mnsAppFrontend#4]
Login fehlgeschlagen, Fehler in json Objekt Zeile 1, kein Login auf dem Server möglich

**Comment by fbae** [comment]
Kann sein, dass für Schüler ein syntaktisch falsches Objekt geliefert wird. Müsste mal überprüft werden. Da wäre es gut zu wissen, was da bemängelt wird.

**Comment by felixblang** [comment]
Für Schüler funktioniert es noch nicht
![login_console_error](https://user-images.githubusercontent.com/28527318/27006588-0b31e654-4e38-11e7-98e1-eb43d401d7f1.JPG)

**Comment by fbae** [comment]
OK, ist hoffentlich morgen gelöst

**Comment by felixblang** [comment]
Auch bei Dateien auf dem Server kein login möglich
![kein_login_moeglich](https://user-images.githubusercontent.com/28527318/27070776-a6d7ed68-501a-11e7-8808-86af2439b8aa.JPG)

**Comment by felixblang** [comment]
Sfari bekommt aus der Datenbank bei einem login-Versuch alle Objekte, jedoch kann es diese anscheinend nicht in einer lokalen Datenbank speichern
![safari_unhandled_rejection](https://user-images.githubusercontent.com/28527318/27345350-ab04fece-55e9-11e7-9940-4e293c3b1049.JPG)

**Comment by fbae** [comment]
Ja, siehe [dexie.org/docs/IndexedDB-on-Safari](http://dexie.org/docs/IndexedDB-on-Safari).
Bleibt also der dort benannte shim oder eine andere Programmierung. Was würdest Du vorschlagen?

**Comment by fbae** [comment]
@Kein Login auf Safari möglich
Ja, siehe [dexie.org/docs/IndexedDB-on-Safari](http://dexie.org/docs/IndexedDB-on-Safari).
Bleibt also der dort benannte shim oder eine andere Programmierung. Was würdest Du vorschlagen?

**Comment by felixblang** [comment]
Der mobile Safari browser auf dem iPhone ist momentan bei version 5 also muss es wohl über den shim laufen..

**Comment by felixblang** [comment]
binden Sie den shim ein, oder soll ich es versuchen?

**Comment by fbae** [comment]
Firefox auf iOS ist scheinbar nicht immer gleich. Felix und Janik B. versucht herauszufinden, woran das liegt.

**Comment by felixblang** [comment]
Jetzt kann man die Seite (zumindest mobil - auf dem pc hab ich es noch nicht versucht) garnicht mehr aufrufen

Forbidden
You do not have permission to access this document.

________________________________
Web Server at niemoeller.schule



Am 28.06.2017 um 23:08 schrieb fbae <notifications@github.com<mailto:notifications@github.com>>:


Firefox auf iOS ist scheinbar nicht immer gleich. Felix und Janik B. versucht herauszufinden, woran das liegt.

**Comment by JanikBuecher** [comment]
Fehler gefunden: Ab IOS 10.3 funktioniert IndexDB bei allen Browsern nicht(<10.3 funktioniert die Seite auch in Safari)

**Comment by JanikBuecher** [comment]
Fehler bei Safari lautet: Failed to load resource: the server responded with a status of 404 (not found)
http://vapp.niemoeller.schule/scripts/vendor/dexie.min.js.map

**Comment by JanikBuecher** [comment]
Er bekommt aber die Daten aus der Datenbank wie es aussieht

**Comment by JanikBuecher** [comment]
![img_3431](https://user-images.githubusercontent.com/28527320/27725641-8c5d3a6e-5d77-11e7-8555-72c9f6fa3e6c.JPG)
