### ISSUE TITLE
Bücherliste wird nur für Schüler benötigt

### ISSUE THREAD

**Issue by fbae** [MartinNiemllerSchule/mnsAppFrontend#6]
Der Menüeintrag der Bücherliste sollte nur für Schüler erscheinen, nicht für Lehrer

**Comment by felixblang** [comment]
Bücherliste ist außerdem zu breit um in angemessener Größe auf manche Handys zu passen. Ist der Punkt "Anschaffungsjahr" notwendig?

**Comment by fbae** [comment]
Nein, Anschaffungsjahr ist unnütz. Aber im Netz finden sich einige Anleitungen, wie Spalten bei Bedarf aus- bzw. eingeblendet werden können beispielsweise [responsive-table-plugins-and-patterns](https://sitesforprofit.com/responsive-table-plugins-and-patterns).
