### ISSUE TITLE
Testdaten müssen bereitgestellt werden

### ISSUE THREAD

**Issue by fbae** [MartinNiemllerSchule/mnsAppFrontend#7]
Die Testdaten für den Lehrer-Account sind jetzt fertig.
Es fehlen noch die Daten für Schüler der Q und der kleineren Klassen.

**Comment by JanikBuecher** [comment]
Sind zur Zeit nur die Leheretestdaten da?

**Comment by fbae** [comment]
Die Testdaten sind vollständig (siehe [wiki](https://github.com/MartinNiemllerSchule/mnsAppFrontend/wiki/Testdaten))
Schüler Q: [test.html?**s**](http://vapp.niemoeller.schule/test.html?s)
Schüler 5. Klasse: [test.html?**5**](vapp.niemoeller.schule/test.html?5)
Lehrer: [test.html?**l**](vapp.niemoeller.schule/test.html?l)

**Comment by fbae** [comment]
Wie schon oben: die Testdaten sind vollständig - genaueres steht im [wiki](https://github.com/MartinNiemllerSchule/mnsAppFrontend/wiki/Testdaten).
Ich schließe den Eintrag.
